### ISSUE TITLE
Log out not always working first time

### ISSUE THREAD

**Issue by Farfi55** [BurnTables/BurnTablesApp#6]

**Comment by Farfi55** [comment]
Serve testare se il logout funziona correttamente adesso

**Comment by ryuk4real** [comment]
Ho testato il logout sul dev e funziona

**Comment by CiccioGallo13** [comment]
pronti

**Comment by Farfi55** [comment]
va bene, io ho avuto qualche problema con il sistema che mi considera loggato ma senza riuscire a comunicare con il server, ho cambiato alcune cose dentro CurrentUserService e quando ricevo un errore segno l'utente come non loggato, vediamo se questo approccio porta a bugs, e nel caso contrario si può chiudere l'issue

**Comment by CiccioGallo13** [comment]
a me funziona
