### ISSUE TITLE
Aggiungere più categorie in esplora

### ISSUE THREAD

**Issue by CiccioGallo13** [BurnTables/BurnTablesApp#7]

**Comment by Farfi55** [comment]
si potrebbero prendere traccie dato un genere, ma i top generi del'utente per ora sono calcolati dentro il componente statistics, @ryuk4real riesci a mettere le statistiche in un oggetto, da inserire dentro `CurrentUserService` in modo da avere un accesso globale a quei dati?
potremmo lasciarlo potenzialmente undefined, e caricare le statistiche solo su richiesta, cioè quando si andrà (per la prima volta) sulla pagina esplora o la propria pagina profilo, o in qualsiasi componente che fa uso delle statistiche
