### ISSUE TITLE
Mettere roba nella home, nuove categorie e un intestazione per il feed

### ISSUE THREAD

**Issue by CiccioGallo13** [BurnTables/BurnTablesApp#8]

**Comment by Farfi55** [comment]
le playlist non sono supportate al momento, quindi sopo ascoltati di recente avrebbe senso

**Comment by CiccioGallo13** [comment]
ok allora quelle più se riesci a fare quella cosa degli album/track ancora da valutare, sennò vedi cosa fornisce spotify e scegli cosa mettere

**Comment by Farfi55** [comment]
implementato traccie e album non ancora recensiti + traccie ascoltate di recente
la pagina ci mette un pò a caricare tutto però
